In [1]:
import tensorflow as tf
import numpy as np

In [12]:
v3 = tf.range(100.0)

In [13]:
v3=tf.reshape(v3, [1,5,5,4], name=None)

In [44]:
with tf.Session() as sess:
    print(sess.run(v3[0][0][1]))
#     print(sess.run(output))

[4. 5. 6. 7.]


In [41]:
[1,]*len(v3.get_shape())

[1, 1, 1, 1]

In [45]:
tf.reshape(v3[0][0][1], [1, 1, 1, -1])

<tf.Tensor 'Reshape_5:0' shape=(1, 1, 1, 4) dtype=float32>

In [17]:
scale_logits_d = tf.transpose(v3[...,None], [0,3,1,2,4])

In [22]:
ksize=3
max_maps = tf.nn.max_pool3d(scale_logits_d, [1,num_scales,ksize,ksize,1], [1,num_scales,1,1,1], padding='SAME')

In [36]:
max_maps.get_shape().as_list()[-1]

1

In [37]:
tf.reshape(v3, [1,-1,1,1,])

<tf.Tensor 'Reshape_4:0' shape=(1, 100, 1, 1) dtype=float32>

In [32]:
a=tf.reduce_max(v3, axis=3, keep_dims=True)
with tf.Session() as sess:
    print(sess.run(a))
a.shape

[[[[ 3.]
   [ 7.]
   [11.]
   [15.]
   [19.]]

  [[23.]
   [27.]
   [31.]
   [35.]
   [39.]]

  [[43.]
   [47.]
   [51.]
   [55.]
   [59.]]

  [[63.]
   [67.]
   [71.]
   [75.]
   [79.]]

  [[83.]
   [87.]
   [91.]
   [95.]
   [99.]]]]


TensorShape([Dimension(1), Dimension(5), Dimension(5), Dimension(1)])

In [31]:
mean, variance = tf.nn.moments(v3, axes=[2,3], keep_dims=True)

In [32]:
outputs = tf.nn.batch_normalization(v3, mean, variance, None, None, 1e-6)

In [35]:
with tf.Session() as sess:
    print(sess.run(outputs))

[[[[-1.5491933  -1.1618949  -0.77459663]
   [-0.38729835  0.          0.38729835]
   [ 0.7745966   1.1618949   1.5491933 ]]]]


In [89]:
v3 = tf.range(49.0)

In [90]:
v2=tf.reshape(v3, [1,7,7,1], name=None)

In [91]:
max_logits = tf.nn.max_pool(v2, [1,3,3, 1],
                            strides=[1,1,1,1], padding='SAME')

In [92]:
sum_filter = tf.constant(np.ones((3,3,1,1)), dtype=tf.float32) 

In [98]:
ex = tf.exp(1.0 * (v2 - max_logits))

In [99]:
sum_ex = tf.nn.conv2d(ex, sum_filter, [1,1,1,1], padding='SAME')

In [100]:
probs = ex / (sum_ex + 1e-6)

In [97]:
probs.shape

TensorShape([Dimension(1), Dimension(7), Dimension(7), Dimension(1)])

In [2]:
with tf.Session() as sess:
    print(sess.run(probs))

NameError: name 'tf' is not defined

In [1]:
with tf.Session() as sess:
    print(sess.run(max_logits))

NameError: name 'tf' is not defined

In [53]:
max_logits.shape

TensorShape([Dimension(1), Dimension(50), Dimension(50), Dimension(1)])