In [55]:
import tensorflow as tf
import numpy as np

In [64]:
v3 = tf.range(25.0)

In [44]:
v3=tf.reshape(v3, [1,1,3,3], name=None)

In [30]:
with tf.Session() as sess:
    print(sess.run(v3))
#     print(sess.run(output))

[[[[0. 1. 2.]
   [3. 4. 5.]
   [6. 7. 8.]]]]


In [31]:
mean, variance = tf.nn.moments(v3, axes=[2,3], keep_dims=True)

In [32]:
outputs = tf.nn.batch_normalization(v3, mean, variance, None, None, 1e-6)

In [35]:
with tf.Session() as sess:
    print(sess.run(outputs))

[[[[-1.5491933  -1.1618949  -0.77459663]
   [-0.38729835  0.          0.38729835]
   [ 0.7745966   1.1618949   1.5491933 ]]]]


In [89]:
v3 = tf.range(49.0)

In [90]:
v2=tf.reshape(v3, [1,7,7,1], name=None)

In [91]:
max_logits = tf.nn.max_pool(v2, [1,3,3, 1],
                            strides=[1,1,1,1], padding='SAME')

In [92]:
sum_filter = tf.constant(np.ones((3,3,1,1)), dtype=tf.float32) 

In [98]:
ex = tf.exp(1.0 * (v2 - max_logits))

In [99]:
sum_ex = tf.nn.conv2d(ex, sum_filter, [1,1,1,1], padding='SAME')

In [100]:
probs = ex / (sum_ex + 1e-6)

In [97]:
probs.shape

TensorShape([Dimension(1), Dimension(7), Dimension(7), Dimension(1)])

In [101]:
with tf.Session() as sess:
    print(sess.run(probs))

[[[[2.4981382e-01]
   [1.6658390e-01]
   [1.6658390e-01]
   [1.6658390e-01]
   [1.6658390e-01]
   [1.0593732e-01]
   [3.6538285e-01]]

  [[1.6658390e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [7.0632316e-02]
   [2.4362110e-01]]

  [[1.6658390e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [7.0632316e-02]
   [2.4362110e-01]]

  [[1.6658390e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [7.0632316e-02]
   [2.4362110e-01]]

  [[1.6658390e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [1.1107432e-01]
   [7.0632316e-02]
   [2.4362110e-01]]

  [[4.5511033e-04]
   [3.0340703e-04]
   [3.0340703e-04]
   [3.0340703e-04]
   [3.0340703e-04]
   [1.9291375e-04]
   [6.6542515e-04]]

  [[4.9954379e-01]
   [3.3302936e-01]
   [3.3302936e-01]
   [3.3302936e-01]
   [3.3302936e-01]
   [2.1174836e-01]
   [7.3039204e-01]]]]


In [51]:
with tf.Session() as sess:
    print(sess.run(max_logits))

[[[[ 357.]
   [ 358.]
   [ 359.]
   ...
   [ 399.]
   [ 399.]
   [ 399.]]

  [[ 407.]
   [ 408.]
   [ 409.]
   ...
   [ 449.]
   [ 449.]
   [ 449.]]

  [[ 457.]
   [ 458.]
   [ 459.]
   ...
   [ 499.]
   [ 499.]
   [ 499.]]

  ...

  [[2457.]
   [2458.]
   [2459.]
   ...
   [2499.]
   [2499.]
   [2499.]]

  [[2457.]
   [2458.]
   [2459.]
   ...
   [2499.]
   [2499.]
   [2499.]]

  [[2457.]
   [2458.]
   [2459.]
   ...
   [2499.]
   [2499.]
   [2499.]]]]


In [53]:
max_logits.shape

TensorShape([Dimension(1), Dimension(50), Dimension(50), Dimension(1)])